### ISSUE TITLE
Cooking steps

### ISSUE THREAD

**Issue by choang91** [The-Student-Cookbook/The-Student-Cookbook#14]
Description: Steps to cook are not there yet. The whole cook process is displayed on a single view.
Severity: Trivial
Suggestion: This probably depends on the database.

**Comment by mdillenbeck** [comment]
Step by step cooking will not be implemented at this time.  Activity changed to display just the single view so as to avoid confusion by the end users.

NOTE: parsing the data from various sources is not a trivial problem; each presents its steps in a different format and thus there is no simple (or even complex) pattern to use - this most likely will be most efficient way is to use human data entry for such a task.
