### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by choang91** [The-Student-Cookbook/The-Student-Cookbook#17]
Description: After hitting the “Home” button on the Profile setting, hitting the Back button leads to the previous view instead of exiting the app.
Severity: Trivial
Suggestion: Check for current view, if it is the Home, then hitting Back will prompt user to exit the app.

**Comment by djohns2021** [comment]
Fixing this would require a rewrite of the app since we designed it using out dated documents. The fix would involve changing all of the activities into fragments and would not be worth the time to change over.
